#!/usr/bin/env python3
"""Generate test files in supported formats for translation testing."""

import json
import sys
from pathlib import Path

TEST_CONTENT = {
    "app": {
        "title": "Welcome to Zellig",
        "subtitle": "Your automatic translation tool",
        "description": "This application helps you translate content from one language to another using advanced AI models.",
    },
    "messages": {
        "greeting": "Hello, how are you today?",
        "farewell": "Goodbye and see you soon!",
        "thanks": "Thank you for using Zellig",
    },
    "nav": {
        "home": "Home",
        "about": "About us",
        "contact": "Contact",
        "settings": "Settings",
    },
    "status": [
        "Loading...",
        "Processing your request",
        "Translation complete",
        "Error occurred",
    ],
}

HEADER = """# Translation test file for Zellig
# Generated by scripts/generate_test_files.py
# Run: zellig translate -i <file> -s en -t fr
"""


def generate_json(path: Path):
    content = TEST_CONTENT.copy()
    content["_header_comment"] = "Zellig translation test file"
    path.write_text(json.dumps(content, indent=2, ensure_ascii=False) + "\n")
    print(f"  {path}")


def generate_markdown(path: Path):
    md = (
        HEADER
        + """# Welcome to Zellig

Zellig is an automatic translation tool that helps you translate content between languages.

## Features

- Automatic language detection
- Support for multiple languages
- AI-powered translations
- Local model support with CTranslate2

## Getting Started

To start using Zellig, follow these steps:

1. Install the tool
2. Configure your preferred model
3. Start translating!

## Example

Here is an example of how to use Zellig:

```
zellig translate "Hello world" -s en -t fr
```

This will translate "Hello world" from English to French.

## Notes

> Zellig is a powerful tool for anyone who needs to translate text quickly and accurately.
"""
    )
    path.write_text(md)
    print(f"  {path}")


def generate_toml(path: Path):
    toml_content = """
[app]
title = "Welcome to Zellig"
subtitle = "Your automatic translation tool"
description = "This application helps you translate content from one language to another."

[messages]
greeting = "Hello, how are you today?"
farewell = "Goodbye and see you soon!"
thanks = "Thank you for using Zellig"

[nav]
home = "Home"
about = "About us"
contact = "Contact"
settings = "Settings"

[status]
loading = "Loading..."
processing = "Processing your request"
complete = "Translation complete"
error = "Error occurred"
"""
    path.write_text(toml_content.lstrip())
    print(f"  {path}")


def generate_xliff(path: Path):
    xliff = """<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" target-language="fr" datatype="plaintext">
    <header>
      <tool tool-id="zellig" tool-name="Zellig"/>
      <note>Translation test file</note>
    </header>
    <body>
      <trans-unit id="1">
        <source>Welcome to Zellig</source>
        <target/>
      </trans-unit>
      <trans-unit id="2">
        <source>Your automatic translation tool</source>
        <target/>
      </trans-unit>
      <trans-unit id="3">
        <source>Hello, how are you today?</source>
        <target/>
      </trans-unit>
      <trans-unit id="4">
        <source>Goodbye and see you soon!</source>
        <target/>
      </trans-unit>
      <trans-unit id="5">
        <source>Home</source>
        <target/>
      </trans-unit>
      <trans-unit id="6">
        <source>Settings</source>
        <target/>
      </trans-unit>
    </body>
  </file>
</xliff>
"""
    path.write_text(xliff.lstrip())
    print(f"  {path}")


def generate_po(path: Path):
    po_content = r"""# Translation test file for Zellig.
# Generated by scripts/generate_test_files.py
#
msgid ""
msgstr ""

msgid "app.title"
msgstr "Welcome to Zellig"

msgid "app.subtitle"
msgstr "Your automatic translation tool"

msgid "app.description"
msgstr "This application helps you translate content from one language to another using advanced AI models."

msgid "messages.greeting"
msgstr "Hello, how are you today?"

msgid "messages.farewell"
msgstr "Goodbye and see you soon!"

msgid "messages.thanks"
msgstr "Thank you for using Zellig"

msgid "nav.home"
msgstr "Home"

msgid "nav.about"
msgstr "About us"

msgid "nav.contact"
msgstr "Contact"

msgid "nav.settings"
msgstr "Settings"

msgid "status.0"
msgstr "Loading..."

msgid "status.1"
msgstr "Processing your request"

msgid "status.2"
msgstr "Translation complete"

msgid "status.3"
msgstr "Error occurred"

msgid "items.message"
msgid_plural "items.messages"
msgstr[0] "%d message"
msgstr[1] "%d messages"

msgid "items.file"
msgid_plural "items.files"
msgstr[0] "%d file"
msgstr[1] "%d files"
"""
    path.write_text(po_content.lstrip())
    print(f"  {path}")


def generate_yaml(path: Path):
    yaml_content = """
app:
  title: "Welcome to Zellig"
  subtitle: "Your automatic translation tool"
  description: "This application helps you translate content from one language to another."

messages:
  greeting: "Hello, how are you today?"
  farewell: "Goodbye and see you soon!"
  thanks: "Thank you for using Zellig"

nav:
  home: "Home"
  about: "About us"
  contact: "Contact"
  settings: "Settings"

status:
  - "Loading..."
  - "Processing your request"
  - "Translation complete"
  - "Error occurred"
"""
    path.write_text(yaml_content.lstrip())
    print(f"  {path}")


def main():
    output_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("test_files")
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating test files in {output_dir}/")

    generators = {
        "test.json": generate_json,
        "test.md": generate_markdown,
        "test.toml": generate_toml,
        "test.xlf": generate_xliff,
        "test.yaml": generate_yaml,
        "test.po": generate_po,
    }

    for filename, gen in generators.items():
        gen(output_dir / filename)


if __name__ == "__main__":
    main()
