/// Language information: (ISO 639-1, NLLB-200 code, English name, Native name)
pub type LanguageInfo = (&'static str, &'static str, &'static str, &'static str);

pub const LANGUAGES: &[LanguageInfo] = &[
    ("", "ace_Arab", "Acehnese", "Acehnese"),
    ("", "ace_Latn", "Acehnese", "Acehnese"),
    ("", "acm_Arab", "Mesopotamian Arabic", "العربية"),
    ("", "acq_Arab", "Ta'izzi-Adeni Arabic", "العربية"),
    ("", "aeb_Arab", "Tunisian Arabic", "تونسي"),
    ("af", "afr_Latn", "Afrikaans", "Afrikaans"),
    ("", "ajp_Arab", "South Levantine Arabic", "العربية"),
    ("", "aka_Latn", "Akan", "Akan"),
    ("", "als_Latn", "Alsatian", "Elsässisch"),
    ("am", "amh_Ethi", "Amharic", "አማርኛ"),
    ("", "apc_Arab", "North Levantine Arabic", "العربية"),
    ("", "arb_Arab", "Modern Standard Arabic", "العربية الفصحى"),
    ("", "ars_Arab", "Najdi Arabic", "العربية"),
    ("", "ary_Arab", "Moroccan Arabic", "الدارجة"),
    ("", "arz_Arab", "Egyptian Arabic", "مصرى"),
    ("", "asm_Beng", "Assamese", "অসমীয়া"),
    ("", "ast_Latn", "Asturian", "Asturianu"),
    ("", "awa_Deva", "Awadhi", "अवधी"),
    ("", "ayr_Latn", "Aymara", "Aymar"),
    ("", "azb_Arab", "North Azerbaijani", "آذربایجانجا"),
    ("", "azj_Latn", "South Azerbaijani", "Azərbaycanca"),
    ("", "bak_Cyrl", "Bashkir", "Башҡортса"),
    ("", "bam_Latn", "Bambara", "Bamanankan"),
    ("", "ban_Latn", "Balinese", "Basa Bali"),
    ("be", "bel_Cyrl", "bel", "bel"),
    ("", "bem_Latn", "Bemba", "Chibemba"),
    ("bn", "ben_Beng", "Bengali", "বাংলা"),
    ("", "bho_Deva", "Bhojpuri", "भोजपुरी"),
    ("", "bjn_Arab", "Banjar", "Banjarese"),
    ("", "bjn_Latn", "Banjar", "Banjarese"),
    ("", "bod_Tibt", "Tibetan", "བོད་སྐད་"),
    ("bs", "bos_Latn", "Bosnian", "Bosanski"),
    ("", "bug_Latn", "Buginese", "Basa Ugi"),
    ("bg", "bul_Cyrl", "Bulgarian", "Български"),
    ("ca", "cat_Latn", "Catalan", "Català"),
    ("ceb", "ceb_Latn", "Cebuano", "Cebuano"),
    ("cs", "ces_Latn", "Czech", "Čeština"),
    ("", "cjk_Latn", "Kinyarwanda", "Ikinyarwanda"),
    ("", "ckb_Arab", "Central Kurdish", "کوردی سۆرانی"),
    ("", "crh_Latn", "Crimean Tatar", "Qırımtatarca"),
    ("cy", "cym_Latn", "Welsh", "Cymraeg"),
    ("da", "dan_Latn", "Danish", "Dansk"),
    ("de", "deu_Latn", "German", "Deutsch"),
    ("", "dik_Latn", "Dinka", "Thuɔŋjäŋ"),
    ("", "dyu_Latn", "Dyula", "Jula"),
    ("", "dzo_Tibt", "dzo", "dzo"),
    ("el", "ell_Grek", "Greek", "Ελληνικά"),
    ("en", "eng_Latn", "English", "English"),
    ("eo", "epo_Latn", "Esperanto", "Esperanto"),
    ("et", "est_Latn", "Estonian", "Eesti"),
    ("eu", "eus_Latn", "Basque", "Euskara"),
    ("ee", "ewe_Latn", "Ewe", "Eʋegbe"),
    ("", "fao_Latn", "fao", "fao"),
    ("fj", "fij_Latn", "Fijian", "Na Vosa Vakaviti"),
    ("fi", "fin_Latn", "Finnish", "Suomi"),
    ("", "fon_Latn", "fon", "fon"),
    ("fr", "fra_Latn", "French", "Français"),
    ("", "fur_Latn", "fur", "fur"),
    ("", "fuv_Latn", "fuv", "fuv"),
    ("", "gaz_Latn", "gaz", "gaz"),
    ("gd", "gla_Latn", "Scottish Gaelic", "Gàidhlig"),
    ("ga", "gle_Latn", "Irish", "Gaeilge"),
    ("gl", "glg_Latn", "Galician", "Galego"),
    ("gn", "grn_Latn", "Guarani", "Avañe'ẽ"),
    ("gu", "guj_Gujr", "Gujarati", "ગુજરાતી"),
    ("ht", "hat_Latn", "Haitian Creole", "Kreyòl Ayisyen"),
    ("ha", "hau_Latn", "Hausa", "Hausa"),
    ("he", "heb_Hebr", "Hebrew", "עברית"),
    ("hi", "hin_Deva", "Hindi", "हिन्दी"),
    ("", "hne_Deva", "Chhattisgarhi", "छत्तीसगढ़ी"),
    ("hr", "hrv_Latn", "Croatian", "Hrvatski"),
    ("hu", "hun_Latn", "Hungarian", "Magyar"),
    ("hy", "hye_Armn", "Armenian", "Հայերեն"),
    ("ig", "ibo_Latn", "Igbo", "Igbo"),
    ("", "ilo_Latn", "Iloko", "Iloko"),
    ("id", "ind_Latn", "Indonesian", "Bahasa Indonesia"),
    ("is", "isl_Latn", "Icelandic", "Íslenska"),
    ("it", "ita_Latn", "Italian", "Italiano"),
    ("jw", "jav_Latn", "Javanese", "ꦧꦱꦗꦮ"),
    ("ja", "jpn_Jpan", "Japanese", "日本語"),
    ("", "kab_Latn", "kab", "kab"),
    ("", "kac_Latn", "kac", "kac"),
    ("", "kam_Latn", "kam", "kam"),
    ("kn", "kan_Knda", "kan", "kan"),
    ("ks", "kas_Arab", "kas", "kas"),
    ("ks", "kas_Deva", "kas", "kas"),
    ("ka", "kat_Geor", "kat", "kat"),
    ("kk", "kaz_Cyrl", "Kazakh", "Қазақша"),
    ("", "kbp_Latn", "kbp", "kbp"),
    ("", "kea_Latn", "kea", "kea"),
    ("", "khk_Cyrl", "khk", "khk"),
    ("km", "khm_Khmr", "Khmer", "ខ្មែរ"),
    ("", "kik_Latn", "kik", "kik"),
    ("rw", "kin_Latn", "Kinyarwanda", "Ikinyarwanda"),
    ("ky", "kir_Cyrl", "Kyrgyz", "Кыргызча"),
    ("", "kmb_Latn", "kmb", "kmb"),
    ("", "kmr_Latn", "kmr", "kmr"),
    ("", "knc_Arab", "knc", "knc"),
    ("", "knc_Latn", "knc", "knc"),
    ("", "kon_Latn", "kon", "kon"),
    ("ko", "kor_Hang", "Korean", "한국어"),
    ("lo", "lao_Laoo", "Lao", "ລາວ"),
    ("", "lij_Latn", "Ligurian", "Lìgure"),
    ("li", "lim_Latn", "lim", "lim"),
    ("ln", "lin_Latn", "lin", "lin"),
    ("lt", "lit_Latn", "Lithuanian", "Lietuvių"),
    ("", "lmo_Latn", "lmo", "lmo"),
    ("", "ltg_Latn", "ltg", "ltg"),
    ("lb", "ltz_Latn", "Luxembourgish", "Lëtzebuergesch"),
    ("", "lua_Latn", "lua", "lua"),
    ("lg", "lug_Latn", "lug", "lug"),
    ("", "luo_Latn", "luo", "luo"),
    ("", "lus_Latn", "lus", "lus"),
    ("", "lvs_Latn", "Latvian", "Latviešu"),
    ("", "mag_Deva", "mag", "mag"),
    ("", "mai_Deva", "mai", "mai"),
    ("ml", "mal_Mlym", "Malayalam", "മലയാളം"),
    ("mr", "mar_Deva", "Marathi", "मराठी"),
    ("", "min_Latn", "min", "min"),
    ("mk", "mkd_Cyrl", "Macedonian", "Македонски"),
    ("mt", "mlt_Latn", "Maltese", "Malti"),
    ("", "mni_Beng", "Manipuri", "মৈতৈলোন"),
    ("", "mos_Latn", "mos", "mos"),
    ("mi", "mri_Latn", "Maori", "Te Reo Māori"),
    ("my", "mya_Mymr", "Burmese", "မြန်မာ"),
    ("nl", "nld_Latn", "Dutch", "Nederlands"),
    ("", "nno_Latn", "Norwegian Nynorsk", "Norsk"),
    ("no", "nob_Latn", "Norwegian Bokmål", "Norsk"),
    ("", "npi_Deva", "Nepali", "नेपाली"),
    ("ns", "nso_Latn", "nso", "nso"),
    ("", "nus_Latn", "nus", "nus"),
    ("ny", "nya_Latn", "Chichewa", "Chichewa"),
    ("oc", "oci_Latn", "Occitan", "Occitan"),
    ("or", "ory_Orya", "Odia", "ଓଡ଼ିଆ"),
    ("", "pag_Latn", "pag", "pag"),
    ("pa", "pan_Guru", "Punjabi", "ਪੰਜਾਬੀ"),
    ("", "pap_Latn", "Papiamento", "Papiamento"),
    ("", "pbt_Arab", "pbt", "pbt"),
    ("", "pes_Arab", "Iranian Persian", "فارسی"),
    ("", "plt_Latn", "plt", "plt"),
    ("pl", "pol_Latn", "Polish", "Polski"),
    ("pt", "por_Latn", "Portuguese", "Português"),
    ("", "prs_Arab", "prs", "prs"),
    ("", "quy_Latn", "quy", "quy"),
    ("ro", "ron_Latn", "Romanian", "Română"),
    ("", "run_Latn", "run", "run"),
    ("ru", "rus_Cyrl", "Russian", "Русский"),
    ("", "sag_Latn", "Sango", "Sängö"),
    ("", "san_Deva", "Sanskrit", "संस्कृतम्"),
    ("", "sat_Beng", "Santali", "ᱥᱟᱱᱛᱟᱲᱤ"),
    ("", "scn_Latn", "Sicilian", "Sicilianu"),
    ("", "shn_Mymr", "Shan", "သျၢင်း"),
    ("si", "sin_Sinh", "Sinhala", "සිංහල"),
    ("sk", "slk_Latn", "Slovak", "Slovenčina"),
    ("sl", "slv_Latn", "Slovenian", "Slovenščina"),
    ("", "smo_Latn", "Samoan", "Gagana Sāmoa"),
    ("sn", "sna_Latn", "Shona", "ChiShona"),
    ("sd", "snd_Arab", "Sindhi", "سنڌي"),
    ("so", "som_Latn", "Somali", "Soomaali"),
    ("st", "sot_Latn", "Southern Sotho", "Sesotho"),
    ("es", "spa_Latn", "Spanish", "Español"),
    ("", "srd_Latn", "Sardinian", "Sardu"),
    ("sr", "srp_Cyrl", "Serbian", "Српски"),
    ("ss", "ssw_Latn", "Swati", "SiSwati"),
    ("su", "sun_Latn", "Sundanese", "Basa Sunda"),
    ("sv", "swe_Latn", "Swedish", "Svenska"),
    ("", "swh_Latn", "Swahili", "Kiswahili"),
    ("", "szl_Latn", "szl", "szl"),
    ("ta", "tam_Taml", "Tamil", "தமிழ்"),
    ("", "taq_Latn", "taq", "taq"),
    ("", "taq_Tfng", "taq", "taq"),
    ("tt", "tat_Cyrl", "Tatar", "Татарча"),
    ("te", "tel_Telu", "Telugu", "తెలుగు"),
    ("tg", "tgk_Cyrl", "Tajik", "Тоҷикӣ"),
    ("tl", "tgl_Latn", "Tagalog", "Tagalog"),
    ("th", "tha_Thai", "Thai", "ไทย"),
    ("ti", "tir_Ethi", "Tigrinya", "ትግርኛ"),
    ("", "tpi_Latn", "Tok Pisin", "Tok Pisin"),
    ("tn", "tsn_Latn", "Tswana", "Setswana"),
    ("ts", "tso_Latn", "Tsonga", "Xitsonga"),
    ("tk", "tuk_Latn", "Turkmen", "Türkmençe"),
    ("", "tum_Latn", "tum", "tum"),
    ("tr", "tur_Latn", "Turkish", "Türkçe"),
    ("tw", "twi_Latn", "Twi", "Twi"),
    ("", "tzm_Tfng", "tzm", "tzm"),
    ("ug", "uig_Arab", "Uyghur", "ئۇيغۇرچە"),
    ("uk", "ukr_Cyrl", "Ukrainian", "Українська"),
    ("", "umb_Latn", "umb", "umb"),
    ("ur", "urd_Arab", "Urdu", "اردو"),
    ("", "uzn_Latn", "uzn", "uzn"),
    ("", "vec_Latn", "vec", "vec"),
    ("vi", "vie_Latn", "Vietnamese", "Tiếng Việt"),
    ("", "war_Latn", "Waray", "Winaray"),
    ("wo", "wol_Latn", "Wolof", "Wolof"),
    ("xh", "xho_Latn", "Xhosa", "isiXhosa"),
    ("", "ydd_Hebr", "ydd", "ydd"),
    ("yo", "yor_Latn", "Yoruba", "Yorùbá"),
    ("", "yue_Hant", "yue", "yue"),
    ("zh", "zho_Hans", "Chinese", "简体中文"),
    ("zh", "zho_Hant", "Chinese", "简体中文"),
    ("ms", "zsm_Latn", "Malay", "Bahasa Melayu"),
    ("zu", "zul_Latn", "Zulu", "isiZulu"),
];

pub fn is_supported(code: &str) -> bool {
    LANGUAGES.iter().any(|(c, _, _, _)| *c == code)
}

pub fn iso_to_nllb(iso_code: &str) -> Option<&'static str> {
    LANGUAGES
        .iter()
        .find(|(iso, _, _, _)| *iso == iso_code)
        .map(|(_, nllb, _, _)| *nllb)
}

pub fn list_languages() {
    use crate::output;
    println!(
        "{}",
        output::bold(format!("Supported languages ({} total)", LANGUAGES.len()))
    );
    println!("{}", output::dim("\u{2500}".repeat(80)));
    println!(
        "{:<8} {:<25} {:<30} {}",
        output::bold("ISO"),
        output::bold("NLLB-200"),
        output::bold("English"),
        output::bold("Native")
    );
    println!("{}", output::dim("\u{2500}".repeat(80)));
    for (iso, nllb, english, native) in LANGUAGES {
        let iso_display = if iso.is_empty() { &nllb[0..3] } else { iso };
        println!("{:<8} {:<25} {:<30} {}", iso_display, nllb, english, native);
    }
}
